#!/bin/bash

# Run with ./tBot

files="testing/examineBot.c 
testing/logChessStructs.c 

src/chessBot/chessBot.c 
src/chessBot/pieceSquareTable.c 

src/chessGameEmulator.c 
src/moveGenerator.c 

src/utils/fenString.c 
src/utils/utils.c 

src/state/board.c 
src/state/gameState.c 
src/state/zobristKey.c 

src/magicBitBoard/magicBitBoard.c 
src/magicBitBoard/rook.c 
src/magicBitBoard/bishop.c"

echo -n "$files" | tr -d '\n' | xargs gcc -Wall -Wextra -Wunused -o examineBot

if [ $? -ne 0 ]; then
    exit 1
fi

./examineBot