#!/bin/bash

# Run this bash file with ./unit 

OUT="$(mktemp /tmp/output.XXXXXXXXXX)" || { echo "Failed to create temp file"; exit 1; }

mkdir -p ./build && cd ./build

cmake -DWHICH=unittest .. >> "$OUT"
cmake --build . >> "$OUT"

if [ $? -ne 0 ]; then
    cat "$OUT"
    printf "\n================== ERROR while compiling with CMake ==================\n"
    exit 1
fi

./unittest