/*
The Windows code was generated by ChatGPT cause I don't code in Windows.
If someone who knows how to use the Windows api wants to refactor this code, be my guest.
*/
#ifdef _WIN32

#include <windows.h>
#include <assert.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

#include "UCIEngineCommunication.h"

struct EngineCommunication {
    HANDLE hInputWrite;   // Parent writes to child's stdin
    HANDLE hOutputRead;   // Parent reads from child's stdout
    HANDLE hProcess;      // Handle to the child process
    FILE* logFile;
};

void UCIEngine_sendCommand_windows(EngineCommunication* engineCommunication, const char* command) {
    DWORD bytesWritten;

    // Ensure the command ends with a newline
    size_t commandLength = snprintf(NULL, 0, "%s\n", command);
    char buffer[commandLength + 1];
    snprintf(buffer, commandLength + 1, "%s\n", command);

    // Note: Do not write the NULL-byte, else ReadFile hangs
    // This is why we do buffer[commandLength + 1] and not add 1 to commandLength when creating it

    BOOL success = WriteFile(
        engineCommunication->hInputWrite,  // Handle to child's stdin
        buffer,                           // Buffer to write
        (DWORD)commandLength,             // Number of bytes to write
        &bytesWritten,                    // Number of bytes actually written
        NULL                              // No overlapped I/O
    );

    if (!success) {
        fprintf(stderr, "Failed to write command to engine (error %lu), exiting...\n", GetLastError());
        exit(EXIT_FAILURE);
    }
    if (bytesWritten != commandLength) {
        fprintf(stderr, "bytesWritten (%lu) != commandLength (%zu), exiting...\n", bytesWritten, commandLength);
        exit(EXIT_FAILURE);
    }

    fprintf(engineCommunication->logFile, "%s\n", command);
}

#define INITIAL_CAPACITY (128)

char* UCIEngine_readResponse_windows(EngineCommunication* engineCommunication, char* data, int capacity) {
    DWORD bytesRead;
    char ch;
    int length = 0;

    if (data == NULL || capacity <= 0) {
        capacity = INITIAL_CAPACITY;
        data = (char*)malloc(capacity);
        assert(data != NULL && "Buy more RAM, lol");
    }

    while (true) {
        BOOL success = ReadFile(
            engineCommunication->hOutputRead,
            &ch,
            1, // Read one byte at a time
            &bytesRead,
            NULL
        );

        if (!success || bytesRead == 0) {
            // Read error or EOF
            fprintf(stderr, "ERROR with ReadFile, we only read %lu bytes, exiting...\n", bytesRead);
            exit(EXIT_FAILURE);
        }

        // Skip carriage return cause of Window line-ending
        if (ch == '\r') continue;

        data[length++] = ch;

        // Resize if needed
        if (length >= capacity - 1) {
            capacity *= 2;
            data = realloc(data, capacity);
            assert(data != NULL && "Buy more RAM, lol");
        }

        // Stop on newline
        if (ch == '\n') break;
    }

    data[length] = '\0'; // Null-terminate
    fprintf(engineCommunication->logFile, "%s", data);
    return data;
}

#define returnOnFail(condition, message) \
    if (condition) {                     \
        fprintf(stderr, message);        \
        free(engineCommunication);       \
        return NULL;                     \
    }                                    \

EngineCommunication* UCIEngine_initialize_windows(const char* enginePath, const char* logFilePath) {
    EngineCommunication* engineCommunication = malloc(sizeof(EngineCommunication));
    HANDLE hChildStdoutRead = NULL;
    HANDLE hChildStdoutWrite = NULL;
    HANDLE hChildStdinRead = NULL;
    HANDLE hChildStdinWrite = NULL;
    SECURITY_ATTRIBUTES saAttr = {
        .nLength = sizeof(SECURITY_ATTRIBUTES),
        .lpSecurityDescriptor = NULL,
        .bInheritHandle = TRUE
    };

    // Create pipes for stdout
    returnOnFail(!CreatePipe(&hChildStdoutRead, &hChildStdoutWrite, &saAttr, 0), "Failed to create stdout pipe\n");
    returnOnFail(!SetHandleInformation(hChildStdoutRead, HANDLE_FLAG_INHERIT, 0), "Failed to set handle info on stdout read\n");
    // Create pipes for stdin
    returnOnFail(!CreatePipe(&hChildStdinRead, &hChildStdinWrite, &saAttr, 0), "Failed to create stdin pipe\n");
    returnOnFail(!SetHandleInformation(hChildStdinWrite, HANDLE_FLAG_INHERIT, 0), "Failed to set handle info on stdin write\n");

    PROCESS_INFORMATION piProcInfo;
    STARTUPINFOA siStartInfo;
    ZeroMemory(&piProcInfo, sizeof(PROCESS_INFORMATION));
    ZeroMemory(&siStartInfo, sizeof(STARTUPINFOA));
    siStartInfo.cb = sizeof(STARTUPINFOA);
    siStartInfo.dwFlags |= STARTF_USESTDHANDLES;
    siStartInfo.hStdInput = hChildStdinRead;
    siStartInfo.hStdOutput = hChildStdoutWrite;
    siStartInfo.hStdError = hChildStdoutWrite;

    // Build mutable command line string (CreateProcessA requires this)
    char commandLine[MAX_PATH];
    snprintf(commandLine, sizeof(commandLine), "\"%s\"", enginePath);

    BOOL success = CreateProcessA(
        NULL,
        commandLine,
        NULL, NULL,
        TRUE,           // Inherit handles
        0,              // Creation flags
        NULL,
        NULL,
        &siStartInfo,
        &piProcInfo
    );

    returnOnFail(!success, "CreateProcess failed\n");

    // Close unneeded pipe ends after process is launched
    CloseHandle(hChildStdoutWrite);
    CloseHandle(hChildStdinRead);

    engineCommunication->hInputWrite = hChildStdinWrite;
    engineCommunication->hOutputRead = hChildStdoutRead;
    engineCommunication->hProcess = piProcInfo.hProcess;

    // Close thread handle (we don’t need it)
    CloseHandle(piProcInfo.hThread);

    engineCommunication->logFile = fopen(logFilePath, "w");
    returnOnFail(engineCommunication->logFile == NULL, "Log file is NULL\n");

    return engineCommunication;
}

void UCIEngine_terminate_windows(EngineCommunication* engineCommunication) {
    // Wait for the engine process to exit (with timeout just in case)
    DWORD result = WaitForSingleObject(engineCommunication->hProcess, 3000); // wait up to 3 seconds

    if (result == WAIT_TIMEOUT) {
        // Engine did not exit in time; forcefully terminate it
        TerminateProcess(engineCommunication->hProcess, 0);
        WaitForSingleObject(engineCommunication->hProcess, INFINITE);
    }

    // Clean up handles
    CloseHandle(engineCommunication->hInputWrite);
    CloseHandle(engineCommunication->hOutputRead);
    CloseHandle(engineCommunication->hProcess);
    
    fflush(engineCommunication->logFile);
    fclose(engineCommunication->logFile);
    free(engineCommunication);
}

#endif
