/*
The Windows code was generated by ChatGPT cause I don't code in Windows.
If someone who knows how to use the Windows api wants to refactor this code, be my guest.
*/
#ifdef _WIN32

#include <windows.h>
#include <assert.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

typedef struct EngineCommunication {
    HANDLE hInputWrite;   // Parent writes to child's stdin
    HANDLE hOutputRead;   // Parent reads from child's stdout
    HANDLE hProcess;      // Handle to the child process
} EngineCommunication;

EngineCommunication engineCommunication;

void UCIEngine_sendCommand_windows(const char* command) {
    DWORD bytesWritten;
    char buffer[1024];

    // Ensure the command ends with a newline
    snprintf(buffer, sizeof(buffer), "%s\n", command);

    BOOL success = WriteFile(
        engineCommunication.hInputWrite,  // Handle to child's stdin
        buffer,                           // Buffer to write
        (DWORD)strlen(buffer),            // Number of bytes to write
        &bytesWritten,                    // Number of bytes actually written
        NULL                              // No overlapped I/O
    );

    if (!success || bytesWritten != strlen(buffer)) {
        fprintf(stderr, "Failed to write command to engine (error %lu), exiting...\n", GetLastError());
        exit(EXIT_FAILURE);
    }
}

#define INITIAL_CAPACITY (128)

char* UCIEngine_readResponse_windows(char* data, int capacity) {
    DWORD bytesRead;
    char ch;
    int length = 0;

    // If data is NULL, allocate an initial buffer
    if (data == NULL || capacity <= 0) {
        capacity = INITIAL_CAPACITY;
        data = (char*)malloc(capacity);
        assert(data != NULL && "Buy more RAM, lol");
    }

    while (true) {
        BOOL success = ReadFile(
            engineCommunication.hOutputRead,
            &ch,                     // Read one byte at a time
            1,
            &bytesRead,
            NULL
        );

        if (!success || bytesRead == 0) {
            // Read error or EOF
            fprintf(stderr, "ERROR with ReadFile, we only read %lu bytes, exiting...\n", bytesRead);
            exit(EXIT_FAILURE);
        }

        // Store the character
        data[length++] = ch;

        // Resize if needed
        if (length >= capacity - 1) {
            capacity *= 2;
            data = realloc(data, capacity);
            assert(data != NULL && "Buy more RAM, lol");
        }

        // Stop on newline
        if (ch == '\n') {
            break;
        }
    }

    data[length] = '\0'; // Null-terminate
    return data;
}

bool UCIEngine_initialize_windows(const char* enginePath) {
    HANDLE hChildStdoutRead = NULL;
    HANDLE hChildStdoutWrite = NULL;
    HANDLE hChildStdinRead = NULL;
    HANDLE hChildStdinWrite = NULL;
    SECURITY_ATTRIBUTES saAttr = {
        .nLength = sizeof(SECURITY_ATTRIBUTES),
        .lpSecurityDescriptor = NULL,
        .bInheritHandle = TRUE
    };

    // Create pipes for stdout
    if (!CreatePipe(&hChildStdoutRead, &hChildStdoutWrite, &saAttr, 0)) {
        fprintf(stderr, "Failed to create stdout pipe\n");
        return false;
    }
    if (!SetHandleInformation(hChildStdoutRead, HANDLE_FLAG_INHERIT, 0)) {
        fprintf(stderr, "Failed to set handle info on stdout read\n");
        return false;
    }

    // Create pipes for stdin
    if (!CreatePipe(&hChildStdinRead, &hChildStdinWrite, &saAttr, 0)) {
        fprintf(stderr, "Failed to create stdin pipe\n");
        return false;
    }
    if (!SetHandleInformation(hChildStdinWrite, HANDLE_FLAG_INHERIT, 0)) {
        fprintf(stderr, "Failed to set handle info on stdin write\n");
        return false;
    }

    PROCESS_INFORMATION piProcInfo;
    STARTUPINFOA siStartInfo;
    ZeroMemory(&piProcInfo, sizeof(PROCESS_INFORMATION));
    ZeroMemory(&siStartInfo, sizeof(STARTUPINFOA));
    siStartInfo.cb = sizeof(STARTUPINFOA);
    siStartInfo.dwFlags |= STARTF_USESTDHANDLES;
    siStartInfo.hStdInput = hChildStdinRead;
    siStartInfo.hStdOutput = hChildStdoutWrite;
    siStartInfo.hStdError = hChildStdoutWrite;

    // Build mutable command line string (CreateProcessA requires this)
    char commandLine[MAX_PATH];
    snprintf(commandLine, sizeof(commandLine), "\"%s\"", enginePath);

    BOOL success = CreateProcessA(
        NULL,
        commandLine,
        NULL,
        NULL,
        TRUE,           // Inherit handles
        0,              // Creation flags
        NULL,
        NULL,
        &siStartInfo,
        &piProcInfo
    );

    // Close unneeded pipe ends after process is launched
    CloseHandle(hChildStdoutWrite);
    CloseHandle(hChildStdinRead);

    if (!success) {
        fprintf(stderr, "CreateProcess failed (error %lu)\n", GetLastError());
        return false;
    }

    engineCommunication = (EngineCommunication){
        .hInputWrite = hChildStdinWrite,
        .hOutputRead = hChildStdoutRead,
        .hProcess = piProcInfo.hProcess
    };

    // Close thread handle (we don’t need it)
    CloseHandle(piProcInfo.hThread);

    return true;
}

void UCIEngine_terminate_windows() {
    // Wait for the engine process to exit (with timeout just in case)
    DWORD result = WaitForSingleObject(engineCommunication.hProcess, 3000); // wait up to 3 seconds

    if (result == WAIT_TIMEOUT) {
        // Engine did not exit in time; forcefully terminate it
        TerminateProcess(engineCommunication.hProcess, 0);
        WaitForSingleObject(engineCommunication.hProcess, INFINITE);
    }

    // Clean up handles
    CloseHandle(engineCommunication.hInputWrite);
    CloseHandle(engineCommunication.hOutputRead);
    CloseHandle(engineCommunication.hProcess);
}

#endif
