#include "AppStyle.h"

// Disclaimer:
// All styles except for the default style were generated by ChatGPT

AppStyle defaultStyle = {
    .backgroundColor = { 30, 30, 30, 255 },
    .modalBgColor = { 200, 200, 200, 255 },
    .creditsColor = { 128, 128, 128, 255 },
    .chessboardStyle = {
        .square1Color = {100, 100, 100, 255},
        .square2Color = {50, 50, 50, 255},
        .highlightSquareColor = { 80, 80, 120, 128 }
    },
    .textStyle = {
        .textColor = WHITE_COLOR,
        .selectedTextColor = WHITE_COLOR,
        .selectedTextBgColor = { 30, 120, 230, 25 }
    },
    .buttonStyle = {
        .idleColor = {40, 40, 40, 255},
        .borderColor = { 200, 200, 200, 255 },
        .hoverColor = { 80, 80, 120, 255 },
        .clickedColor = { 120, 120, 160, 255 }
    },
    .checkboxStyle = {
        .borderColor = { 80, 80, 120, 255 },
        .hoverColor = { 200, 200, 200, 255 },
        .checkedColor = WHITE_COLOR
    },
    .scrollbarStyle = {
        .idleColor = { 75, 75, 75, 255 },
        .hoverColor = { 111, 111, 111, 255 },
        .clickedColor = { 140, 140, 140, 255 }
    }
};

AppStyle midnightBlueStyle = {
    .backgroundColor = { 15, 20, 30, 255 },
    .modalBgColor = { 40, 45, 60, 255 },
    .creditsColor = { 100, 120, 160, 255 },
    .chessboardStyle = {
        .square1Color = {70, 85, 110, 255},
        .square2Color = {40, 50, 70, 255},
        .highlightSquareColor = { 80, 120, 200, 100 }
    },
    .textStyle = {
        .textColor = { 230, 230, 255, 255 },
        .selectedTextColor = { 255, 255, 255, 255 },
        .selectedTextBgColor = { 70, 120, 220, 40 }
    },
    .buttonStyle = {
        .idleColor = { 30, 40, 60, 255 },
        .borderColor = { 90, 110, 160, 255 },
        .hoverColor = { 60, 80, 120, 255 },
        .clickedColor = { 90, 110, 150, 255 }
    },
    .checkboxStyle = {
        .borderColor = { 80, 110, 160, 255 },
        .hoverColor = { 120, 150, 200, 255 },
        .checkedColor = { 230, 230, 255, 255 }
    },
    .scrollbarStyle = {
        .idleColor = { 45, 55, 75, 255 },
        .hoverColor = { 70, 90, 130, 255 },
        .clickedColor = { 100, 120, 160, 255 }
    }
};

AppStyle forestGreenStyle = {
    .backgroundColor = { 25, 35, 25, 255 },
    .modalBgColor = { 60, 80, 60, 255 },
    .creditsColor = { 150, 180, 150, 255 },
    .chessboardStyle = {
        .square1Color = { 85, 110, 85, 255 },
        .square2Color = { 45, 60, 45, 255 },
        .highlightSquareColor = { 100, 150, 100, 100 }
    },
    .textStyle = {
        .textColor = { 230, 255, 230, 255 },
        .selectedTextColor = { 255, 255, 255, 255 },
        .selectedTextBgColor = { 50, 150, 100, 40 }
    },
    .buttonStyle = {
        .idleColor = { 50, 70, 50, 255 },
        .borderColor = { 160, 200, 160, 255 },
        .hoverColor = { 70, 110, 70, 255 },
        .clickedColor = { 90, 130, 90, 255 }
    },
    .checkboxStyle = {
        .borderColor = { 100, 140, 100, 255 },
        .hoverColor = { 160, 200, 160, 255 },
        .checkedColor = { 255, 255, 255, 255 }
    },
    .scrollbarStyle = {
        .idleColor = { 60, 80, 60, 255 },
        .hoverColor = { 90, 120, 90, 255 },
        .clickedColor = { 110, 140, 110, 255 }
    }
};

AppStyle solarizedLightStyle = {
    .backgroundColor = { 250, 245, 230, 255 },
    .modalBgColor = { 240, 230, 210, 255 },
    .creditsColor = { 150, 140, 120, 255 },
    .chessboardStyle = {
        .square1Color = { 238, 232, 213, 255 },
        .square2Color = { 181, 137, 0, 255 },
        .highlightSquareColor = { 255, 220, 120, 128 }
    },
    .textStyle = {
        .textColor = { 60, 50, 40, 255 },
        .selectedTextColor = { 255, 255, 255, 255 },
        .selectedTextBgColor = { 38, 139, 210, 40 }
    },
    .buttonStyle = {
        .idleColor = { 220, 210, 190, 255 },
        .borderColor = { 90, 80, 60, 255 },
        .hoverColor = { 181, 137, 0, 255 },
        .clickedColor = { 133, 94, 0, 255 }
    },
    .checkboxStyle = {
        .borderColor = { 90, 80, 60, 255 },
        .hoverColor = { 181, 137, 0, 255 },
        .checkedColor = { 38, 139, 210, 255 }
    },
    .scrollbarStyle = {
        .idleColor = { 220, 210, 190, 255 },
        .hoverColor = { 181, 137, 0, 255 },
        .clickedColor = { 133, 94, 0, 255 }
    }
};

AppStyle royalPurpleStyle = {
    .backgroundColor = { 25, 20, 35, 255 },
    .modalBgColor = { 50, 40, 70, 255 },
    .creditsColor = { 160, 130, 200, 255 },
    .chessboardStyle = {
        .square1Color = { 90, 70, 130, 255 },
        .square2Color = { 45, 35, 70, 255 },
        .highlightSquareColor = { 150, 100, 200, 100 }
    },
    .textStyle = {
        .textColor = { 240, 230, 255, 255 },
        .selectedTextColor = { 255, 255, 255, 255 },
        .selectedTextBgColor = { 180, 120, 255, 40 }
    },
    .buttonStyle = {
        .idleColor = { 50, 40, 70, 255 },
        .borderColor = { 150, 120, 200, 255 },
        .hoverColor = { 90, 70, 130, 255 },
        .clickedColor = { 120, 100, 160, 255 }
    },
    .checkboxStyle = {
        .borderColor = { 150, 120, 200, 255 },
        .hoverColor = { 200, 170, 240, 255 },
        .checkedColor = { 255, 255, 255, 255 }
    },
    .scrollbarStyle = {
        .idleColor = { 70, 55, 100, 255 },
        .hoverColor = { 100, 80, 130, 255 },
        .clickedColor = { 130, 110, 160, 255 }
    }
};
