/*
Note: Test were generated by ChatGPT
After careful review they are correct
*/

#include "../../src/utils/CharBuffer.h"

#include <assert.h>
#include <stdio.h>
#include <string.h>

bool test_string_compareStrings() {
    bool actual;
    bool expected;

    // Test case: "hello", "hello"
    expected = true;
    actual = string_compareStrings("hello", "hello");

    if (expected != actual) {
        printf("ERROR: string_compareStrings(\"hello\", \"hello\")\n");
        printf("\tExpected: %s\n", expected ? "true" : "false");
        printf("\tActual: %s\n", actual ? "true" : "false");
        return false;
    }

    // Test case: "Hello", "hello"
    expected = false;
    actual = string_compareStrings("Hello", "hello");

    if (expected != actual) {
        printf("ERROR: string_compareStrings(\"Hello\", \"hello\")\n");
        printf("\tExpected: %s\n", expected ? "true" : "false");
        printf("\tActual: %s\n", actual ? "true" : "false");
        return false;
    }

    // Test case: "", ""
    expected = true;
    actual = string_compareStrings("", "");

    if (expected != actual) {
        printf("ERROR: string_compareStrings(\"\", \"\")\n");
        printf("\tExpected: %s\n", expected ? "true" : "false");
        printf("\tActual: %s\n", actual ? "true" : "false");
        return false;
    }

    return true;
}

bool test_string_nextSpaceCharacterFromIndex() {
    size_t actual;
    size_t expected;

    // Test case: "hello world", 0
    expected = 5;
    actual = string_nextSpaceCharacterFromIndex("hello world", 0);

    if (expected != actual) {
        printf("ERROR: string_nextSpaceCharacterFromIndex(\"hello world\", 0)\n");
        printf("\tExpected: %zu\n", expected);
        printf("\tActual: %zu\n", actual);
        return false;
    }

    // Test case: "hello world", 6
    expected = 11;
    actual = string_nextSpaceCharacterFromIndex("hello world", 6);

    if (expected != actual) {
        printf("ERROR: string_nextSpaceCharacterFromIndex(\"hello world\", 6)\n");
        printf("\tExpected: %zu\n", expected);
        printf("\tActual: %zu\n", actual);
        return false;
    }

    // Test case: "helloworld", 0 (no spaces)
    expected = 10;
    actual = string_nextSpaceCharacterFromIndex("helloworld", 0);

    if (expected != actual) {
        printf("ERROR: string_nextSpaceCharacterFromIndex(\"helloworld\", 0)\n");
        printf("\tExpected: %zu\n", expected);
        printf("\tActual: %zu\n", actual);
        return false;
    }

    // Test case: " ", 0 (single space character)
    expected = 0;
    actual = string_nextSpaceCharacterFromIndex(" ", 0);

    if (expected != actual) {
        printf("ERROR: string_nextSpaceCharacterFromIndex(\" \", 0)\n");
        printf("\tExpected: %zu\n", expected);
        printf("\tActual: %zu\n", actual);
        return false;
    }

    // Test case: "hello world", 20 (out of bounds)
    expected = 11;
    actual = string_nextSpaceCharacterFromIndex("hello world", 20);

    if (expected != actual) {
        printf("ERROR: string_nextSpaceCharacterFromIndex(\"hello world\", 20)\n");
        printf("\tExpected: %zu\n", expected);
        printf("\tActual: %zu\n", actual);
        return false;
    }

    return true;
}

bool test_string_toLower() {
    char test1[] = "HELLO";
    char expected1[] = "hello";
    string_toLower(test1);

    if (strcmp(test1, expected1) != 0) {
        printf("ERROR: string_toLower(\"HELLO\")\n");
        printf("\tExpected: \"%s\"\n", expected1);
        printf("\tActual: \"%s\"\n", test1);
        return false;
    }

    char test2[] = "HeLLo WoRLD";
    char expected2[] = "hello world";
    string_toLower(test2);

    if (strcmp(test2, expected2) != 0) {
        printf("ERROR: string_toLower(\"HeLLo WoRLD\")\n");
        printf("\tExpected: \"%s\"\n", expected2);
        printf("\tActual: \"%s\"\n", test2);
        return false;
    }

    char test3[] = "";
    char expected3[] = "";
    string_toLower(test3);

    if (strcmp(test3, expected3) != 0) {
        printf("ERROR: string_toLower(\"\")\n");
        printf("\tExpected: \"%s\"\n", expected3);
        printf("\tActual: \"%s\"\n", test3);
        return false;
    }

    return true;
}


bool test_string_parseNumber() {
    int actual;
    int expected;

    // Test case: "123"
    expected = 123;
    actual = string_parseNumber("123");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\"123\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "0"
    expected = 0;
    actual = string_parseNumber("0");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\"0\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "99999"
    expected = 99999;
    actual = string_parseNumber("99999");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\"99999\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "42abc"
    expected = -1;
    actual = string_parseNumber("42abc");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\"42abc\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "abc42"
    expected = -1;
    actual = string_parseNumber("abc42");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\"abc42\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "-42"
    expected = -1;
    actual = string_parseNumber("-42");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\"-42\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: " 42"
    expected = -1;
    actual = string_parseNumber(" 42");
    if (expected != actual) {
        printf("ERROR: string_parseNumber(\" 42\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    return true;
}

bool test_string_algebraicToIndex() {
    int actual;
    int expected;

    // Test case: "a1"
    expected = 56;
    actual = string_algebraicToIndex("a1");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"a1\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "h1"
    expected = 63;
    actual = string_algebraicToIndex("h1");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"h1\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "a8"
    expected = 0;
    actual = string_algebraicToIndex("a8");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"a8\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "h8"
    expected = 7;
    actual = string_algebraicToIndex("h8");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"h8\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "d4"
    expected = 35;
    actual = string_algebraicToIndex("d4");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"d4\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "-"
    expected = 0;
    actual = string_algebraicToIndex("-");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"-\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "j9" (Invalid square)
    expected = -1;
    actual = string_algebraicToIndex("j9");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"j9\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    // Test case: "a0" (Invalid square)
    expected = -1;
    actual = string_algebraicToIndex("a0");
    if (expected != actual) {
        printf("ERROR: string_algebraicToIndex(\"a0\")\n");
        printf("\tExpected: %d\n", expected);
        printf("\tActual: %d\n", actual);
        return false;
    }

    return true;
}

bool Test_CharBuffer() {
    if (!test_string_compareStrings()) return false;
    if (!test_string_compareStrings()) return false;
    if (!test_string_nextSpaceCharacterFromIndex()) return false;
    if (!test_string_toLower()) return false;
    if (!test_string_parseNumber()) return false;
    if (!test_string_algebraicToIndex()) return false;
    return true;
}
