/*
DISCLAIMER: The following tests were mostly generated by ChatGPT.
Of course the generated was reviewed to make sure it behave properly.

Why did I generate these test by an llm instead of writing them by hand?
Unit test are tedious to write, because they all follow the same structure 
and making them have expressive error messages in case of a test case failing 
takes a lot of time. However, the fact that there is an easy pattern to 
write unit tests makes this a good case for llm to generate them. With this,
I can give the llm the function prototype with its associated documentation and 
the llm can try to generated a unit test in this style:

bool test_<function name to test>() {
    ...

    expected = expected_output;
    actual = <function name to test>(...);

    if (expected != actual) {
        printf("ERROR: <function to test>(...)\n");
        printf("\tExpected: <expected>\n");
        printf("\tActual: <actual>\n");
        return false;
    }

    ...
    return true;
}

Note that this generation of unit test can have the side effect 
of missing edge cases, so I try to spot them when I look at the 
generated tests.

*/

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

#include "tests/TestCharBuffer.h"
#include "tests/TestFenString.h"
#include "tests/TestMath.h"
#include "tests/testBoard.h"
#include "tests/TestTranspositionTable.h"

typedef bool (*TestFunction)(void);

typedef struct Test {
    TestFunction testFunction;
    char* name;
} Test;


void runTest(Test test) {
    printf("Starting %s tests...\n", test.name);
    if (!test.testFunction()) {
        printf("ERROR: %s tests failed :(\n", test.name);
        exit(EXIT_FAILURE);
    }
}

Test tests[] = {
    { Test_CharBuffer, "Char Buffer" },
    { Test_FenString, "Fen String" },
    { Test_Math, "Math" },
    { Test_Board, "Board" },
    { Test_TranspositionTable, "Transposition Table"}
};

// To run: ./unit
int main(void) {

    size_t nbTests = sizeof(tests) / sizeof(Test);

    clock_t begin = clock();

    for (size_t testIndex = 0; testIndex < nbTests; testIndex++) {
        runTest(tests[testIndex]);
    }

    clock_t end = clock();
    double fullTestTimeSpent = (double)(end - begin) / CLOCKS_PER_SEC;
    printf("\nAll unit tests passed in %fms\n", fullTestTimeSpent * 1000);
    return 0;
}
